[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:login-server]
command=/home/RTK/rtk/login-server
directory=/home/RTK/rtk
priority=10
autostart=true
autorestart=true
startretries=10
stdout_logfile=/home/RTK/rtk/logs/login-stdout.log
stderr_logfile=/home/RTK/rtk/logs/login-stderr.log

[program:char-server]
command=/home/RTK/rtk/char-server
directory=/home/RTK/rtk
priority=20
autostart=true
autorestart=true
startretries=10
stdout_logfile=/home/RTK/rtk/logs/char-stdout.log
stderr_logfile=/home/RTK/rtk/logs/char-stderr.log

[program:map-server]
command=/home/RTK/rtk/map-server
directory=/home/RTK/rtk
priority=30
autostart=true
autorestart=true
startretries=10
stdout_logfile=/home/RTK/rtk/logs/map-stdout.log
stderr_logfile=/home/RTK/rtk/logs/map-stderr.log
