onScriptedTile = function(player)
	onSign(player, 2)
	onScriptedTilesQuest(player)
	onScriptedTilesNagnangShieldQuest(player)
	onScriptedTilesMap(player)
	onScriptedTilesBushTree(player)
	onScriptedTilesKanShop(player)
	onScriptedTilesRandomMerchant(player)
	onScriptedTilesArena(player)
	onScriptedTilesElixir(player)
	onScriptedTilesCarnage(player)
	onScriptedTilesPathHalls(player)
	onScriptedTilesTutorsHaven(player)
	onScriptedTilesMythic(player)
	onScriptedTilesMythicFallRooms(player)
	onScriptedTilesSubpath(player)
	onScriptedTilesSubpathCircle(player)
	onScriptedTilesMarket(player)

	--onScriptedTilesJadeCitadel(player)

	onWalk(player)
end
